name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build client Docker image
      run: docker build -f ./client/Dockerfile.dev -t eggop1992/react-test ./client
    - name: Run tests
      run: docker run -e CI=true eggop1992/react-test npm test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build client Docker image
      run: docker build -t eggop1992/prod-fib-client ./client
    - name: Build server docker image 
      run: docker build -t eggop1992/prod-fib-server ./server   
    - name: Build nginx docker image
      run: docker build -t eggop1992/prod-fib-nginx ./nginx
    - name: Build worker docker image
      run: docker build -t eggop1992/prod-fib-worker ./worker
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push images to docker hub
      run: |
        docker push eggop1992/prod-fib-client
        docker push eggop1992/prod-fib-server
        docker push eggop1992/prod-fib-nginx
        docker push eggop1992/prod-fib-worker

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: multi-docker
        environment_name: multi-docker-env
        version_label: 0.0.${{ github.run_number }}
        #0.0.${{ github.run_number }}
        region: eu-north-1
        deployment_package: deploy.zip
