name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build client Docker image
      run: docker build -f ./client/Dockerfile.dev -t eggop1992/react-test ./client
    - name: Run tests
      run: docker run eggop1992/react-test npm test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build client Docker image
      run: docker build -t eggop1992/prod-fib-client:latest ./client
    - name: Build server docker image 
      run: docker build -t eggop1992/prod-fib-server:latest ./server   
    - name: Build nginx docker image
      run: docker build -t eggop1992/prod-fib-nginx:latest ./nginx
    - name: Build worker docker image
      run: docker build -t eggop1992/prod-fib-worker:latest ./worker
